### ISSUE TITLE
Error making API request.  403  upon secret sync

### ISSUE THREAD

**Issue by reggie-k** [argoproj-labs/argocd-vault-plugin#217]
Working with Argocd 1.8.1, plugin version 1.4.0.
Upon an attempt to sync a secret with placeholders , the following error ioccurs on ArgoCD side:
 Error making API request. URL: GET https://my-vault.my-sub-domain.my-domain:8200/v1/my/secret/argo-secret Code: 403

Using k8s auth method on vault side.

Have verified that:
- The SA token argocd repo server container runs with is auto-mounted into argocd repo server container
- Login to vault cli with the token copied from .avp/config.json in the repo server container from a local station works just fine
- vault kv get my/secret/argo-secret  from a local station  gets the secret just fine

Trying to run the plugin for debugging purposes in the repo server container, get an error:
argocd-vault-plugin generate ./
"Error: could not read YAML/JSON files: [could not read file: .avp/config.json from disk: Object 'Kind' is missing"
I see that vault env variables are present in the container when I run printenv.

**Comment by redox72** [comment]
@reggie-k What was the fix?

**Comment by DimitarKapashikov** [comment]
I have the same error when I run argocd-vault-plugin generate for a second time, no clue why the JSON file is getting corrupted, anyone with the same issue?
