### ISSUE TITLE
Any plan to support 1Password

### ISSUE THREAD

**Issue by Klaudioz** [argoproj-labs/argocd-vault-plugin#235]
Hello, do you have any plan to support [1Password Kubernetes Operator](https://github.com/1Password/onepassword-operator)?

**Comment by werne2j** [comment]
Hi @Klaudioz It is not in our immediate backlog but we can take a look. We also accept contributions so if you or anyone else would like to contribute 1password as a backend we would love to review and work to get it into the plugin.

**Comment by josephlim75** [comment]
If you are using vault, you can install 1password plugin so that vault can sync with 1password.  The you can use argocd vault to retrieve from 1password vault secret path

**Comment by werne2j** [comment]
Support released in https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.10.0

**Comment by maxisam** [comment]
@werne2j Thanks for making this work. However, it is not base64 encoded when I pull it. Is it possible to encode it? or an option to do it? Thanks!
