### ISSUE TITLE
How to use the plug-in in a multi-tenant environment? 



### ISSUE THREAD

**Issue by shailsirohi** [argoproj-labs/argocd-vault-plugin#283]
We are using argocd as our CD solution to maintain remote EkS cluster deployments. 
Teams are onboarded to a specific namespace, bound to a argo project and only a restricted set of target clusters are allowed in this project.  
Since, each namespace belongs to a different team, they also have a different AWS Secret Manager instance in their respective AWS accounts.   
On reading the documentation, it feels like only 1 set of AWS creds can be configured. Any thoughts on how we can switch AWS credentials based on namespace

**Comment by werne2j** [comment]
This is also being discussed here. https://github.com/argoproj-labs/argocd-vault-plugin/issues/284 

> This should help: #230 (comment). The idea is you set the AVP_ env vars in the Application spec so that you can set them on an app by app basis depending on which Vault namespace that app needs its secrets from

Hopefully that will help get you in the right direction!

**Comment by werne2j** [comment]
@shailsirohi You can find official documentation on multi tenancy here! https://argocd-vault-plugin.readthedocs.io/en/latest/config/#multitenancy
