### ISSUE TITLE
cli -s do not parse secret name/namespace properly

### ISSUE THREAD

**Issue by yknx4** [argoproj-labs/argocd-vault-plugin#287]
**Describe the bug**
When I run the following command `argocd-vault-plugin generate - -s argocd-vault-config-dev` it returns this error `failed exit status 1: Error: secrets "argocd" is forbidden: User "system:serviceaccount:argocd:default" cannot get resource "secrets" in API group "" in the namespace "argocd-vault-config-dev"` 

It is parsing the namespace as the secret's name, and the secret's name as the namespace

**To Reproduce**
1. Run `argocd-vault-plugin generate - -s argocd-vault-config-dev`

**Expected behavior**
If it is a permission issues, it should be `Error: secrets "argocd-vault-config-dev" is forbidden: User "system:serviceaccount:argocd:default" cannot get resource "secrets" in API group "" in the namespace "argocd"`

**Comment by jkayani** [comment]
While we try to reproduce and fix, can you verify you're using the latest release?

**Comment by werne2j** [comment]
This issue has been resolved in https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.8.0

**Comment by JESWINKNINAN** [comment]
This issue is still getting in the version 1.12.0
