### ISSUE TITLE
Question: Difference between argocd-vault-plugin and external secrets?

### ISSUE THREAD

**Issue by StevenACoffman** [argoproj-labs/argocd-vault-plugin#289]
What I'm wondering is how using [argoproj-labs/argocd-vault-plugin](https://github.com/argoproj-labs/argocd-vault-plugin)  differs from using [external secrets](https://external-secrets.io/) with ArgoCD? It might be a helpful add to your documentation generally.

##### Background

In the existing [ArgoCD secret management documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/secret-management/), while it mentions several popular kubernetes secrets solutions... it doesn't really have any guidance or instructions for how to get them to work specifically with ArgoCD.

It is at least also perhaps noting in that document that the [argoproj-labs/argocd-vault-plugin](https://github.com/argoproj-labs/argocd-vault-plugin) supports not only HashiCorp Vault, but also GCP Secret Manager, AWS Secrets Manager, Azure Key Vault, and IBM Cloud Secrets Manager. Or is this support still in beta?

I found that there was a pretty good write-up on using [external secrets](https://external-secrets.io/) with ArgoCD in this [Kubernetes External Secrets](https://blog.oddbit.com/post/2021-09-03-kubernetes-external-secrets/) article. [External secrets](https://external-secrets.io/)  also supports AWS  Secrets Manager, Azure Key Vault, Google Secret Manager, IBM Cloud Secrets Manager, and HashiCorp Vault like argocd-vault-plugin does. (external secrets also supports addition to Akeyless, Yandex, Gitlab, Oracle and webhooks)

Anyway, I am wondering how these two similar things differ from one another and what the pros and cons are. Thanks for any insight or guidance!

**Comment by werne2j** [comment]
Thanks for the question @StevenACoffman! The first thing that i will point you is this talk https://www.youtube.com/watch?v=7L6nSuKbC2c from KubeCon. It lays out what the goal for this project was and how it differs from others. 

But at the end of the day, these tools are looking to solve the same problem but in different ways. This tool works as CLI tool or plugin to Argo CD to help inject secrets into Kubernetes Secret files using a templating system. 

Something like External Secrets makes use of Custom Resources and an Operator to generate a Kubernetes Secret from the provided Custom Resource. 

So multiple ways to try and solve you GitOps secrets problems. Hope that helps clear things up!

**Comment by StevenACoffman** [comment]
Oh, so [argoproj-labs/argocd-vault-plugin](https://github.com/argoproj-labs/argocd-vault-plugin) uses resource annotations to find and update manifests in place?

**Comment by werne2j** [comment]
@StevenACoffman Correct. That KubeCon talk should lay it all out for you.

**Comment by StevenACoffman** [comment]
This was extremely helpful (both the video and your pointers). Thanks for the great work!
