### ISSUE TITLE
Fix edit uri in mkdocs.yaml

### ISSUE THREAD

**Issue by ernelio** [argoproj-labs/argocd-vault-plugin#290]
**Describe the bug**

On the mkdocs static site, when clicking on the edit page, a 404 not found is received because it redirects to the master branch that does not exist, the correction is to put it to point to the main branch.

**To Reproduce**
1. Go to 'https://argocd-vault-plugin.readthedocs.io/en/stable/'
2. Click on 'edit'

**Expected behavior**
Page correct in github.com

**Screenshots**

**Additional context**

**Comment by werne2j** [comment]
Thanks for the contribution @ernelio! The change will only be reflected in the `latest` version of the docs until we release a new version.
