### ISSUE TITLE
Description of key -s have diametrically opposed description with reality

### ISSUE THREAD

**Issue by 0m1xa** [argoproj-labs/argocd-vault-plugin#294]
**Describe the bug**
`-s, --secret-name string   name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>`
But the plugin uses namespace:name like this `name:namespace`

**To Reproduce**
`cat /tmp/manifest.yaml | argocd-vault-plugin generate -s argocd230rc:argocd-vault-plugin-clientdemo -`

> cat /tmp/manifest.yaml | argocd-vault-plugin generate -s argocd230rc:argocd-vault-plugin-clientdemo -  
Error: secrets "argocd230rc" is forbidden: User "system:serviceaccount:argocd230rc:default" cannot get resource "secrets" in API group "" in the namespace "argocd-vault-plugin-clientdemo"

**Expected behavior**
Option -s parses secret in another namespace as declared

**Additional context**
`argocd-vault-plugin version`
argocd-vault-plugin v1.7.0 (cfd17486e894c9df5a8aa342967e164e800e16f8) BuildDate: 2022-01-25T15:53:59Z```

**Comment by werne2j** [comment]
We are aware of the issue https://github.com/argoproj-labs/argocd-vault-plugin/issues/287 and there has been a fix implemented. We just need to release it.

**Comment by werne2j** [comment]
Issue has been fixed here https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.8.0
