### ISSUE TITLE
Question/Feature - Enable cross account access for AWS Secrets Manager

### ISSUE THREAD

**Issue by ricardojdsilva87** [argoproj-labs/argocd-vault-plugin#316]
Hello,

I have a question if currently the argo secrets plugin supports the retrieval of secrets from a different AWS account?
On the backend configuration for AWS Secrets Manager there is the option for 2 variables:
https://argocd-vault-plugin.readthedocs.io/en/stable/backends/#aws-secrets-manager

Is there the possibility to add a 3rd one? The account number for example?
The arn for the secrets manager looks like this:
```
arn:aws:secretsmanager:<REGION>:<ACCOUNT_NUMBER>:secret:<SECRET_ID>
```
On the account level we would just need to guarantee that the correct IAM permissions were set to access the accounts secrets manager (A simpler getsecrets for all resources should be enough).

Thank you

**Comment by sidewinder12s** [comment]
Yes it does, like the AWS Documentation notes to use secrets manager cross account you need to use the full secret ARN (though you can still use the 'friendly' name of the secret; <SECRET_ID> not <SECRET_ID-random>)

Might just be a doc update.

**Comment by ricardojdsilva87** [comment]
Hello,
I've quickly tested the usage of the arn of a different account and it's working, the argocd vault plugin tries to replace the arn with the needed value. I couldn't find it on the documentation, maybe I can add some more information under the plugin configuration? Most of the examples are for vault.
I would create a PR with the needed changes here:
https://argocd-vault-plugin.readthedocs.io/en/stable/backends/#aws-secrets-manager

The usage looks something like this for a simple secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: namespace
stringData:
  username: <path:arn:aws:secretsmanager:<REGION>:<ACCOUNT_NUMBER>:< SECRET_ID >#<key>>
type: Opaque
```
In this case I got the following error because I hadn't time yet to test the needed permissions (need to create new KMS keys and policies to cross account access), but you can see that argo tries to replace the secret by accessing the external account:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/12953702/157831378-398644c7-7c15-4a4a-ae02-ab14b8dac6f3.png">

Found the following article about the needed change on permissions for reference:
https://aws.amazon.com/premiumsupport/knowledge-center/secrets-manager-share-between-accounts/
https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_examples_cross.html

Thank you for your help again!
