### ISSUE TITLE
feature: add `linux/s390x` support

### ISSUE THREAD

**Issue by skuethe** [argoproj-labs/argocd-vault-plugin#327]
**Is your feature request related to a problem? Please describe.**
I want to use this plugin on zLinux system with s390x arch.
It can then also be used in the upcoming s390x ArgoCD images (work in progress).

**Describe the solution you'd like**
Add `s390x` to goreleaser. I will open a PR

**Describe alternatives you've considered**
-

**Additional context**
As goreleaser is used, changes are minimal to the release automation.

**Comment by jkayani** [comment]
Thanks for the PR for this - let us know if we haven't done a release by the time the Argo CD images are ready for that arch. We usually only release when there are new features so if there aren't any by then I guess we can just add s390x binaries to the latest existing one. Will keep this issue open until then

**Comment by werne2j** [comment]
s390x binary released in new release https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.11.0
