### ISSUE TITLE
Does argocd-vault-plugin support Argo CD's GnuPG signature verification feature?

### ISSUE THREAD

**Issue by colinwilson** [argoproj-labs/argocd-vault-plugin#340]
**Describe the bug**
argocd-vault-plugin (avp) seems to interfere with the functioning of [Argo CD's GnuPG signature verification feature](https://argo-cd.readthedocs.io/en/stable/user-guide/gpg-verification/). 

**To Reproduce**
1. Import GnuPG public keys to Argo CD
2. Configure an app with avp + sync against commits that are signed with the imported key
3. Attempt to sync app
4. Argo CD reports, `Found signature made with RSA key 3091F3F0438C79A3, but verification result was invalid: 'gpg: Can't check signature: No public key'`

**Expected behavior**
For the app to successfully sync with signed commits (like it does when the app is created without `--config-management-plugin argocd-vault-plugin`):

**Screenshots**
App created **with** argocd-vault-plugin + GnuPG signature verification:
```
argocd app create secrets --repo https://github.com/colinwilson/argocd-micro-example-apps.git --path secrets --dest-server https://kubernetes.default.svc --dest-namespace default --config-management-plugin argocd-vault-plugin --sync-policy automated --self-heal
```
Error:
![2022-05-04 20_20_37-secrets - Application Details Tree - Argo CD — Mozilla Firefox](https://user-images.githubusercontent.com/12916656/166812265-5237d255-5940-4cd2-b4d8-0e51c374ae22.png)
<hr>

![2022-05-04 20_21_04-secrets - Application Details Tree - Argo CD — Mozilla Firefox](https://user-images.githubusercontent.com/12916656/166812565-1d32a6a4-28b5-4fe0-9fa8-f08b5aa6cb1a.png)

App created **without** **argocd-vault-plugin** + GnuPG signature verification:
```
argocd app create secrets --repo https://github.com/colinwilson/argocd-micro-example-apps.git --path secrets --dest-server https://kubernetes.default.svc --dest-namespace default --sync-policy automated --self-heal
```
![2022-05-05 21_00_49-traefik-whoami - Application Details Tree - Argo CD — Mozilla Firefox](https://user-images.githubusercontent.com/12916656/167062759-219dd8c6-744e-461d-97ea-a3f504a69897.jpg)

**Additional context**

```
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T01:52:36Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by werne2j** [comment]
@colinwilson we have not tested that behavior. Would need to do some investigating on how it works within Argo CD. 

My guess is since AVP handles working with templates instead of Argo CD natively that functionality is lost.

**Comment by colinwilson** [comment]
> My guess is since AVP handles working with templates instead of Argo CD natively that functionality is lost.

@werne2j Thanks. My guess too but wasn't sure.
