### ISSUE TITLE
Does the plugin support retrieving secrets without specifying the secrets key

### ISSUE THREAD

**Issue by justin-obn** [argoproj-labs/argocd-vault-plugin#342]
I've got such a JSON secret in vault under some `path`:
```
  {
    "a": {
      "secret": "123"
    },
    "b": {
      "secret": "345"
    },
    "c": {
      "secret": "567"
    }
  }
```

Is it possible to retrieve this whole JSON object by just specifying the path?

I would like to be able to retrieve this whole object by just specifying the path to the secret, without giving a specific key, because I want the full object

**Comment by werne2j** [comment]
Hi @justin-obn as long as you put that json under a key in a secret it should work.

So you would have a path `kv/data/something` and at that path you have a key `somejson` with your json as the value.

Then you can do `<path:kv/data/something#somejson` In your yaml.

**Comment by justin-obn** [comment]
Thanks for the info @werne2j
