### ISSUE TITLE
Getting full secret as json

### ISSUE THREAD

**Issue by paveq** [argoproj-labs/argocd-vault-plugin#354]
I'm attempting to create dockerconfigjson secret to store image pull secret (a json document). Json document it stored in Vault.

I've tried following inline syntax to get it:

`<path:avp/data/directory/serviceaccount | base64encode>`

This does not seem to get picked up to AVP at all.

Specifying a key from the document does work:
`<path:avp/data/directory/serviceaccount#auth_uri | base64encode>`

But allows to access only specific field at the time, not entire document inline at once.

Is there any other solution than creating json document in the Vault in such way, that there's some key like "data" and entire serviceAccount json is stored under it already base64 encoded?

**Comment by jkayani** [comment]
Currently this doesn't work as you expect - each placeholder has to have a specific key of the secret and there is no generic key to return the whole secret. If I understand you correctly, you've taken a secret and split out its key-value pairs into a Vault secret. 

The best workaround is to either put the entire JSON under one key in the Vault secret rather than dispersed across many keys, or to reconstruct the JSON in the YAML template, like:
```
...
stringData: |
  { "foo": <path:avp/data/secret#foo>
    "bar": <path:avp/data/secret#bar> 
  }
```

**Comment by paveq** [comment]
@jkayani thanks for clarification!

I went with route of having entire JSON document (ServiceAccount key from GCP) base64 encoded under one key. However, I still get error with: 

`Invalid value: "<secret contents redacted>": invalid character '\n' in string literal.`

This is weird, as I'm passing only base64 one line string here. I attempted to pass the exact same thing in annotation, and for sure there are some extra characters and line change there:
![Screenshot 2022-06-15 at 9 49 03](https://user-images.githubusercontent.com/130256/173761197-1e584b9a-cf28-451d-846f-9eb95e072d17.png)

**Comment by paveq** [comment]
My secret is basically:
`apiVersion: v1
kind: Secret
metadata:
  name: imagepull-secret
  annotations:
    test: "<path:avp/data/somestuff/serviceaccount#key>"`

I would expect rendered result to be:
`apiVersion: v1
kind: Secret
metadata:
  name: imagepull-secret
  annotations:
    test: "ewog..."`

Not having this extra newline and characters there.

**Comment by eeriksen** [comment]
@paveq How did you solve this exactly?

**Comment by richardscholtens** [comment]
@paveq, how did you get it working with the vault? My workaround for now is using Kustomize and a `.dockerconfigjson.env` in which I put the JSON structure.

First create the base64 `AUTH_TOKEN` base64.

```shell
echo -n "username:password" | base64 -w0
```
Then create a JSON structure and add it to `.dockerconfigjson.env`.

```json
{"auths":{"<IMAGE_REGISTRY_URL>"{"username":"<USERNAME>","password":"<PASSWORD>","email":"<EMAIL>","auth":"<AUTH_TOKEN>"}}}
```

Then create the following Kustomize resource.

```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <NAME_SPACE>
secretGenerator:
- name: image-registry-credentials
  files:
  - .dockerconfigjson=.dockerconfigjson.env
  type: kubernetes.io/dockerconfigjson
generatorOptions:
  disableNameSuffixHash: true
```

Then run Kustomize.

```shell
kubectl apply -k <KUSTOMIZE_RESOURCE>
```

This will create a secret called `image-registry-credentials`.

Still I want to be able to store the .dockerconfigjson in the Vault. Do you have any advice?
