### ISSUE TITLE
Supported auth method for getting secrets from Vault

### ISSUE THREAD

**Issue by brysk** [argoproj-labs/argocd-vault-plugin#357]
According to [Backend](https://argocd-vault-plugin.readthedocs.io/en/stable/backends/) section of documentation only  AppRole and Github Auth methods are supported for getting secrets from Vault but the same page describes different ways of auth like Kubernetes Auth and Vault Token. Can you please confirm what's currently supported or not?

**Comment by werne2j** [comment]
> We support AppRole and Github Auth Method for getting secrets from Vault.

This is outdated. If there is a section for it then it is supported. Approle, GitHub, Token and K8s.

**Comment by jkayani** [comment]
Feel free to open a PR to remove that statement if you feel it's misleading!
