### ISSUE TITLE
[docs] argocd-vault-plugin-helm examples don't work since ArgoCD 2.4 due to new environment variables names

### ISSUE THREAD

**Issue by isaacpz** [argoproj-labs/argocd-vault-plugin#359]
**Describe the bug**
On any ArgoCD cluster since version 2.4, the examples on the [With Helm section of the usage page](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm) no longer work correctly. When using those code snippets, all environment variables are empty, even if the application manifest includes valid `env` values.

This is because of the [newly-prefixed environment variables](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.3-2.4/#update-plugins-to-use-newly-prefixed-environment-variables) in ArgoCD version 2.4. This change means that using environment variables like `${helm_args}` or `$HELM_VALUES` will no longer work correctly, and they need to be replaced with `${ARGOCD_ENV_helm_args}` and`$ARGOCD_ENV_HELM_VALUES` in the docs.

**To Reproduce**
Follow the [`with helm` section](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm) in the docs

**Expected behavior**
argocd-vault-plugin correctly works with helm when following the docs

**Comment by werne2j** [comment]
Thanks @isaacpz we are aware and working on support https://github.com/argoproj-labs/argocd-vault-plugin/pull/356

**Comment by werne2j** [comment]
@brysk We have an open PR at the moment, you can follow that here #356.

**Comment by werne2j** [comment]
Support for 2.4 added in https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.12.0
