### ISSUE TITLE
Generate on folder with empty Yaml

### ISSUE THREAD

**Issue by AlexanderProschek** [argoproj-labs/argocd-vault-plugin#363]
**Describe the bug**
When pointing Argo Vault Plugin at a directory with one or more exclusively empty yaml files, AVP throws an error and causes ArgoCD apps to enter into the `unknown` state. Having a source folder with exclusively empty yamls is not an issue with either a pure ArgoCD application, nor when manually deploying the manifests with kubectl, leading me to believe AVP should not have an issue with this either.

```
/tmp/argocd-vault-plugin on main !1 ❯ ls /tmp/example      
a.yaml
/tmp/argocd-vault-plugin on main !1 ❯ cat /tmp/example/a.yaml                                                    
/tmp/argocd-vault-plugin on main !1 ❯ go run main.go generate /tmp/example/                                                                                                              took 5s
Error: No manifests
Usage:
  argocd-vault-plugin generate <path> [flags]

Flags:
  -c, --config-path string         path to a file containing Vault configuration (YAML, JSON, envfile) to use
  -h, --help                       help for generate
  -s, --secret-name string         name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>
      --verbose-sensitive-output   enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr

exit status 1
/tmp/argocd-vault-plugin on main ❯
```

While `kubectl` is fine processing this file (doing nothing)

```
/tmp/argocd-vault-plugin on main ❯ kubectl diff -f /tmp/example
/tmp/argocd-vault-plugin on main ❯
```

As per [section 7.2 of the yaml 1.2 specification](https://yaml.org/spec/1.2.2/#72-empty-nodes):
> YAML allows the node content to be omitted in many cases. Nodes with empty content are interpreted as if they were plain scalars with an empty value. Such nodes are commonly resolved to a “null” value.

Looking into this, the root cause of the issue seems to be [these lines](https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/cmd/generate.go#L78-L80=), so simply removing these lines would put AVP more in line with the behavior of kubectl.

**To Reproduce**
1. Create a folder with an empty yaml
2. Run `argocd-vault-plugin generate /tmp/example/`

**Expected behavior**
Empty output to stdout since that's what is defined in the nodes of the empty yaml file(s)

**Comment by pgrosslicht** [comment]
We're also currently running in this issue. Seeing as the fix is already merged, would it be possible to make a new release containing the fix?
Thanks!

**Comment by werne2j** [comment]
The fix for this was released in https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.13.0
