### ISSUE TITLE
AVP sidecar installation doesn't work

### ISSUE THREAD

**Issue by IvanovOleg** [argoproj-labs/argocd-vault-plugin#376]
**Describe the bug**
I've created an argocd instance using manifests from https://github.com/argoproj-labs/argocd-vault-plugin/tree/main/manifests/cmp-sidecar and argocd doesn't have any plugin in the portal. When I try to create an app and choose the plugin option, the list is empty.

**To Reproduce**
1. Use https://github.com/argoproj-labs/argocd-vault-plugin/tree/main/manifests/cmp-sidecar manifests
2. Try to create app

**Expected behavior**
Plugins appear in the list

**Screenshots/Verbose output**
![plugin](https://user-images.githubusercontent.com/9047397/178913886-9fafc948-e833-466f-bdf0-d962fd4c69b3.jpg)

If you've tried running `argocd-vault-plugin generate` with `--verbose-sensitive-output` to help debug, please include that output here after redacting any secrets.

**Additional context**

**Comment by IvanovOleg** [comment]
`config management plugin not supported. plugin name argocd-vault-plugin-kustomize`

**Comment by werne2j** [comment]
@jkayani Correct me if i am wrong, but with the sidecar pattern, the plugin wont be listed in the dropdown but instead automatically detected based on the discover rules. 

https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#using-a-cmp
```
If your CMP is defined as a sidecar, you must manually define the Application manifest. Do not configure a name field in the plugin section. The plugin will be automatically matched with the Application based on its discovery rules.
```

**Comment by IvanovOleg** [comment]
@werne2j Yes, removing plugin configuration from the app fixed that issue.
