### ISSUE TITLE
Must provide a supported Vault Type

### ISSUE THREAD

**Issue by BMonsalvatge** [argoproj-labs/argocd-vault-plugin#380]
**Describe the bug**
I am currently trying to setup the plugin via the sidecar method with k8s auth using vault as my backend.  However I am consistently getting the following error:

```
Unable to save changes: application spec for cert-manager is invalid: InvalidSpecError: Unable to generate manifests in cert-manager: rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `sh -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . | argocd-vault-plugin generate - ` failed exit status 1: Error: Must provide a supported Vault Type Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>
```

**To Reproduce**
1. Try syncing with secret.  
2. Check argocd-repo-server logs

**Expected behavior**
I would expect it to generate the secret with the inject kv from vault, but I think I am missing a step.  I've also tried define the plugin details via environment variables in the project definition:
```
  plugin:
    env:
      - name: VAULT_ADDR
        value: vault
      - name: AVP_AUTH_TYPE
        value: k8s
      - name: AVP_TYPE
        value: vault
      - name: AVP_K8S_ROLE
        value: argo-cd-argocd-repo-server
```

**Additional context**
Using the kustomize files from https://github.com/argoproj-labs/argocd-vault-plugin/tree/main/manifests/cmp-sidecar

**Comment by werne2j** [comment]
What version of Argo CD and what version of AVP are you using?

**Comment by BMonsalvatge** [comment]
Argo CD: 2.4.7
AVP: I was running 1.11, just updated to 1.12 and now having issues with the volumes for the sidecar container and init:

```
one or more objects failed to apply, reason: Deployment.apps "argo-cd-argocd-repo-server" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: "tmp", spec.template.spec.containers[0].volumeMounts[1].name: Not found: "custom-tools", spec.template.spec.containers[1].volumeMounts[2].name: Not found: "tmp", spec.template.spec.containers[1].volumeMounts[3].name: Not found: "cmp-plugin", spec.template.spec.containers[1].volumeMounts[4].name: Not found: "custom-tools", spec.template.spec.initContainers[1].volumeMounts[0].name: Not found: "custom-tools"]
```

I swapped out using the kustomize patch and instead tried including the init container and sidecar into the helm chart itself (using the manifest from the kustomize example), in order to get the mounting error above... But I am thinking that's probably more due to me missing something at the moment (stilling digging through that).

**Comment by BMonsalvatge** [comment]
Managed to sort out my volume issues, just bad indenting...

Currently I think I got a little farther... New error:
```
ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `sh -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . | argocd-vault-plugin generate - ` failed exit status 1: Error: Must provide a supported Vault Type, received dmF1bHQK Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name> --verbose-sensitive-output enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr
```

I got this error when the values in the `vault-configuration` `stringData` secret weren't base64 encoded, so I updated that.  Still got the same error, so I changed it from `stringData` to `data`, but now I get the following:

```
ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `sh -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . | argocd-vault-plugin generate - ` failed exit status 1: Error: Must provide a supported Vault Type, received vault Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name> --verbose-sensitive-output enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr
```

On the container itself I have the following environment variables set (from the secret) within the containers in the repo server pod:

```
AVP_SECRET_ID=
AVP_TYPE=vault
AVP_AUTH_TYPE=k8s
AVP_K8S_ROLE=argo-cd-argocd-repo-server
AVP_VERSION=1.12.0
AVP_ROLE_ID=
```

**Comment by BMonsalvatge** [comment]
Was able to get it all resolved by changing my file to the config:
```
apiVersion: v1
data:
  # Will be renamed to ARGOCD_ENV_AVP_AUTH_TYPE by ArgoCD before reaching the plugin.
  VAULT_ADDR: aHR0cDovL3ZhdWx0LnZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjgyMDA=
  AVP_AUTH_TYPE: azhz
  AVP_TYPE: dmF1bHQ=
  AVP_K8S_ROLE: YXJnb2Nk
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
```

Issue was mainly related to what was reported here: https://github.com/argoproj-labs/argocd-vault-plugin/issues/301#issuecomment-1045181117

Opening up #381 to handle new issue

**Comment by vijaymhaske** [comment]
Hi @BMonsalvatge,

I am also getting the same error while using argocd vault plugin with sidecar container. Just to provide more contexts:

I have an init container that is downloading the AVP binary and mounting it to both AVP container and repo-server.
Secrets are mounted to repo-server for connecting to vault. secrets are already base64 encoded.

But still getting the same error. :(

rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `argocd-vault-plugin generate .` failed exit status 1: Error: Must provide a supported Vault Type Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>

**Comment by sujith-es** [comment]
Hi @vijaymhaske I am also getting the same error. Are you able to resolve the issue?
