### ISSUE TITLE
Add Support for Vault Userpass Auth Method

### ISSUE THREAD

**Issue by sakiib** [argoproj-labs/argocd-vault-plugin#387]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The `userpass` auth method allows users to authenticate with Vault using a `username` and `password` combination.

- https://www.vaultproject.io/docs/auth/userpass
- https://www.vaultproject.io/api-docs/auth/userpass

**Describe alternatives you've considered**
N/A

**Additional context**
PR: #388

**Comment by werne2j** [comment]
This feature was released in https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.13.0
