### ISSUE TITLE
Question: when argocd-vault-plugin logins to vault?

### ISSUE THREAD

**Issue by ira-gordin-sap** [argoproj-labs/argocd-vault-plugin#399]
Hi,
I was sure that the plugin logins to vault only in case it needs to fetch the credentials from vault, and this happens when argocd hard refresh happens or the repository changes.
Is it true?
Thanks,
Ira

**Comment by werne2j** [comment]
AVP should attempt to authenticate with Vault on the initial Argo CD App creation and sync, whenever Argo CD detects a manifest change and on a hard refresh. When running the plugin as just a CLI, it will attempt to authenticate every time. 

We do have a mechanism to try and cache the Vault token, so that AVP does not have to get a new token every time there is a change https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#caching-the-hashicorp-vault-token

Hope that helps.

**Comment by werne2j** [comment]
What i mean is that AVP does not HAVE to be run with Argo CD in K8s. Just explaining the scenario of when AVP is ran outside of Argo CD. So since that case does not apply to you, you can ignore it.

**Comment by ira-gordin-sap** [comment]
> AVP should attempt to authenticate with Vault on the initial Argo CD App creation and sync, whenever Argo CD detects a manifest change and on a hard refresh. When running the plugin as just a CLI, it will attempt to authenticate every time.
> 
> We do have a mechanism to try and cache the Vault token, so that AVP does not have to get a new token every time there is a change https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#caching-the-hashicorp-vault-token
> 
> Hope that helps.

Yes, it helps! Thank you so much!

**Comment by werne2j** [comment]
If the file doesn't exist there was an issue writing, most likely permissions..
https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/pkg/auth/vault/kubernetes.go#L65
https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/pkg/utils/util.go#L86

**Comment by ira-gordin-sap** [comment]
```"Could not write token to file, will need to login to Vault on subsequent runs:"```
Will it login to Vault all the time? Even no Argo CD detection a manifest change and hard refresh happened?

**Comment by ira-gordin-sap** [comment]
> `"Could not write token to file, will need to login to Vault on subsequent runs:"` I don't see these errors in argocd-repo-server log even on time of sync after manifest change. Where and how can I find the plugin logs?
> 
> Will the plugin login to Vault all the time? Even no Argo CD detection a manifest change and hard refresh happened?

@werne2j do you have an answer?

**Comment by ira-gordin-sap** [comment]
@werne2j could you please respond?

**Comment by werne2j** [comment]
> Will the plugin login to Vault all the time? Even no Argo CD detection a manifest change and hard refresh happened?

yes, vault login happens every time AVP runs

**Comment by ira-gordin-sap** [comment]
> > Will the plugin login to Vault all the time? Even no Argo CD detection a manifest change and hard refresh happened?
> 
> yes, vault login happens every time AVP runs

What do you mean "every time AVP runs"? Can it run even no Argo CD detection a manifest change and hard refresh happened?

**Comment by werne2j** [comment]
> What do you mean "every time AVP runs"? Can it run even no Argo CD detection a manifest change and hard refresh happened?

I mean, whenever Argo CD calls AVP, it will run the login unless it finds a token file like described above. AVP is just a CLI tool and can't call itself. I think your question is really when does Argo CD run the plugin init/generate, so you are better off asking in Argo CD about when that happens.
