### ISSUE TITLE
Examples other than Kind: Secret please

### ISSUE THREAD

**Issue by rp-jasonp** [argoproj-labs/argocd-vault-plugin#405]
"This plugin can be used not just for secrets but also for deployments, configMaps or any other Kubernetes resource."

The only way we have been able to get this plugin to work is via Kind:Secrets, per the application examples folder. Any other use, particularly configmap / helm values.yaml would be appreciated.

**Comment by werne2j** [comment]
Other types work the exact same as secrets, you can see an example here https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/fixtures/input/nonempty/full.yaml and doing a quick search through Github can find a lot of different examples.

https://github.com/pavib0403/vault/blob/main/nginx/templates/secret.yaml - ConfigMap
https://github.com/catenax-ng/maintenance-dashboard/blob/main/chart/templates/secrets.yaml - Helm

Hope that helps!
