### ISSUE TITLE
Selector does not match template labels

### ISSUE THREAD

**Issue by raj13aug** [argoproj-labs/argocd-vault-plugin#419]
**Describe the bug**

I am trying to setting up argocd-vault-plugin and chooses the init container method to install the plugin.

I copied the entire deployment object from below link. 

https://argocd-vault-plugin.readthedocs.io/en/stable/installation/#initcontainer-and-configuration-via-argocd-cm-configmap

Running `kubectl apply -f deployment.yml` would return a `selector does not match template labels` error in terminal.

**Screenshots/Verbose output**

![image](https://user-images.githubusercontent.com/5330003/198557154-44f72de9-a58a-4f98-a3d1-341562288575.png)

**Comment by werne2j** [comment]
That is more of a patch than a whole deployment. You will need to build you deployment using this as an example and not a fully formed deployment
