### ISSUE TITLE
[Feature] Upgrade Azure SDK for GO, support Azure Workload Identity 

### ISSUE THREAD

**Issue by jeffpuckett** [argoproj-labs/argocd-vault-plugin#421]
**Is your feature request related to a problem? Please describe.**
Request to update the Azure SDK for Go version to v7.0. This will require a change in how the SDK is used. 

My underlying request: Microsoft has a new option to authenticate with Azure resources. https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview To use the new authentication method, the Azure SDK For Go should be updated. Example implementation is here: https://github.com/Azure/azure-workload-identity/tree/main/examples/msal-go

(By implementing this, one would not need to store a client secret, token, or username/password in the cluster to authenticate with the vault resource. Which would be awesome.)

**Describe the solution you'd like**
Ways this could be implemented:
- upgrading the library wholesale
- using the AVP_AUTH_TYPE environment variable to support "workloadidentity" or something like that as a way to say use the new SDK and API

**Describe alternatives you've considered**
No alternates yet, although I do hope to clone the repo and implement soon.

**Additional context**

**Comment by jserpapinto** [comment]
Yeah, we would like this too.. 
We have been integrating workload identity into our clusters, but couldn't make it work with argocd-vault-plugin.

I had to use the csi secrets managed identity to be able to retrieve secrets from the key vault in azure.

Not sure what is the best approach.

**Comment by jserpapinto** [comment]
We too have this problem. We want o have workload identity on the plugin sidecar container and we couldn't do it.

I think the `AVP_AUTH_TYPE` could still be `azurekeyvault`, but if the plugin doesn't find a `AZURE_CLIENT_ID`  env var, it should expect that the the identity is being managed at an external level.

Looking forward to seeing this integrated into the plugin!

**Comment by avdicl** [comment]
+1

**Comment by asahnovskiy-deloitte** [comment]
+1

**Comment by werne2j** [comment]
Released in https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.18.0
