### ISSUE TITLE
supplying AWS Authentication

### ISSUE THREAD

**Issue by raj13aug** [argoproj-labs/argocd-vault-plugin#422]
**Describe the bug**

I am try to integrate the vault plugin with AWS secret manager, But backend configure supplying AWS credentials (  AWS_ACCESS_KEY_ID: "<AWS ACCESS KEY ID>" AWS_SECRET_ACCESS_KEY: "<AWS SECRET ACCESS KEY>"). So I don't want to provide the AWS Access Key into backend configure. Is it any other way to integrate IAM role to backend vault plugin rather than AWS Access Key?

If it's yes then provide the document for same.

**Screenshots/Verbose output**

please find the screen shot for supplying AWS credentials.

![image](https://user-images.githubusercontent.com/5330003/198940577-1d8283d1-9a24-40f6-8493-d4c505676b35.png)

Regards,
Nataraj.R

**Comment by werne2j** [comment]
We are non descriptive when it comes to AWS authentication through the client. https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/pkg/config/config.go#L168 

So you can use whatever method of authentication you want. You can find those methods here. https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials
