### ISSUE TITLE
Allow indentation for multiline strings in yaml strings of different indentation levels

### ISSUE THREAD

**Issue by mulhotavares** [argoproj-labs/argocd-vault-plugin#451]
**Is your feature request related to a problem? Please describe.**
I'm trying to use a multiline string that is used on multiple places in a public helm chart.

I came across this [issue](https://github.com/argoproj-labs/argocd-vault-plugin/issues/297) which implemented the `indent` function, but unfortunately, `indent` doesn't help with the case where the same value is used on multiple places with different indentation levels in the helm chart.

**Describe the solution you'd like**
Ideally, the plugin should be able to identify the indentation required for that particular string and follow that automatically depending on the context. Manually specifying an indentation, in this case, is not an option because the indentation required depends on the context.

**Describe alternatives you've considered**
I tried playing around with different `indent`s, but that didn't work. 
Another alternative I tried was to replace the placeholders from the values files before doing helm template.
That didn't seem to work either, as argocd-vault-plugin compains with
```
Error: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in
```
So I'm guessing it only works with actual k8s resources, not with values files.
If we could use argocd-vault-plugin with a values file, a workaround would be to use it before `helm template`, instead of after it.

**Additional context**
Basically I'm trying to install Linkerd helm chart, as documented [here](https://linkerd.io/2.12/tasks/install-helm/), but via ArgoCD.
([linkerd-control-plane)](https://github.com/linkerd/linkerd2/tree/main/charts/linkerd-control-plane).
app-version: 2.12.3
[chart-version 1.9.5](https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane/1.9.5)
[chart-source](https://github.com/linkerd/linkerd2/tree/stable-2.12.3/charts/linkerd-control-plane)

The helm install/template command requires 3 certificates to be passed:
```
helm install linkerd-control-plane \
  -n linkerd \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer.key \
  linkerd/linkerd-control-plane
```

So I created an Argocd application to read those values from secrets, like this:
```
    plugin:
      env:
      - name: HELM_VALUES
        value: |
          identityTrustAnchorsPEM: |
            <path:kv-argocd#linkerd-ca-crt>
          identity:
            issuer:
              tls:
                crtPEM: |
                  <path:kv-argocd#linkerd-issuer-crt | indent 8>
                keyPEM: |
                  <path:kv-argocd#linkerd-issuer-key | indent 8>
```

`indent` works great on the last 2 values, but not for `identityTrustAnchorsPEM`. The reason is that this value will be put in 2 different places:
https://github.com/linkerd/linkerd2/blob/stable-2.12.3/charts/linkerd-control-plane/templates/identity.yaml#L35
and indirectly by dumping all Values here:
https://github.com/linkerd/linkerd2/blob/stable-2.12.3/charts/linkerd-control-plane/templates/config.yaml#L38

If I apply it like that, the cert is correctly replaced on the first yaml, but the identation will be wrong on the second one:

```
apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBjjCCATSgAwIBAgIRAL6OjxDYswXXodeFAG600iEwCgYIKoZIzj0EAwIwJTEj
...
```
vs

```
apiVersion: v1
data:
...
    identityTrustAnchorsPEM: |
      -----BEGIN CERTIFICATE-----
    MIIBjjCCATSgAwIBAgIRAL6OjxDYswXXodeFAG600iEwCgYIKoZIzj0EAwIwJTEj
```

If I change the place holder to 
```
          identityTrustAnchorsPEM: |
            <path:kv-argocd#linkerd-ca-crt | indent 2>
```
I fix the second one, but I break the first one:

```
apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
      MIIBjjCCATSgAwIBAgIRAL6OjxDYswXXodeFAG600iEwCgYIKoZIzj0EAwIwJTEj
...
```

Although this might seem like an edge case, I think having a value being used on different places is probaly not that unlikely. Maybe a bit more unlikely to have one of this places to be an yaml as string inside another yaml...

**Comment by avdicl** [comment]
This is a frustrating issue. I recommend adding [block chomping indicators](https://yaml-multiline.info/) to the Linkerd ConfigMap(s). You can also see [this issue](https://github.com/linkerd/linkerd2/issues/10012) for context.

**Comment by avdicl** [comment]
Creating additional modifiers for the argocd vault plugin could solve the issue instead of making changes in public helm charts. For my Linkerd identityTrustAnchorsPEM issue practically identical to the one here, having `nindent` as a modifier on my inline-path placeholder would have solved the issue.

**Comment by ppapp92** [comment]
Sorry to revive an old thread but I'm also facing a similar issue.  Even the <path:kv-argocd#linkerd-issuer-crt | indent 8> are causing problems in the secret that gets generated.

Did you manage to solve the issue and deploy Linkerd using AVP?
