### ISSUE TITLE
Hi team could you provide full proper documentation for azure key vault what env variables i need to use step be step

### ISSUE THREAD

**Issue by ValdasDienas** [argoproj-labs/argocd-vault-plugin#455]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by werne2j** [comment]
If you look in the docs (https://argocd-vault-plugin.readthedocs.io/en/stable/backends/#azure-key-vault) you will see `Refer to the Use environment-based authentication in the Azure SDK for Go.` which points to https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization#use-environment-based-authentication which describes how to authenticate to Key Vault using the same pattern as all the other backends.

In the future, please be kinder with your words.

**Comment by ValdasDienas** [comment]
So you are building a service and forwarding to read ms documentation. What a nice thing. Is that so hard just to put everything in the place and there wont be any question any more

**Comment by jelicics** [comment]
But the documentation is a flaming piece of shit.
