### ISSUE TITLE
Exiting apps not working after argo vault plugin deployment

### ISSUE THREAD

**Issue by hper4278** [argoproj-labs/argocd-vault-plugin#477]
I’m working on setting up argo vault plugin with exiting Argo-cd (app of apps setup) and i’m referring [this medium doc](https://luafanti.medium.com/injecting-secrets-from-vault-into-helm-charts-with-argocd-43fc1df57e74)

argo vault plugin version 1.13.1
ArgoCD version 5.26.0

but as soon as i deploy new argo helm with reposerver config all of my exiting apps are going to OutOfSync mode with below error
```
SyncError
Skipping sync attempt to 129e3c65d32ab628ed5fa4d26a982441ea353d09: auto-sync will wipe out all resources
```

and when i sync with PRUNE option all of the pods are getting deleted
has anyone face this issue or know a way to sort this?

**Comment by hper4278** [comment]
I was able to get this sorted after adding init stage 

```apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-vault-plugin-helm
spec:
  allowConcurrency: true
  discover:
    find:
      command:
        - sh
        - "-c"
        - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
  init:
    command:
      - bash
      - "-c"
      - |
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo add cluster-autoscaler https://kubernetes.github.io/autoscaler
        helm dependency build
  generate:
    command:
      - bash
      - "-c"
      - |
        helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
        argocd-vault-plugin generate -s argo-cd:argocd-vault-plugin-credentials -
  lockRepo: false
```

**Comment by Emmerson-Miranda** [comment]
In my case I also got "auto-sync will wipe out all resources", the error was originated because the values yaml file wasn't well formatted.
