### ISSUE TITLE
Hashicorp Vault - 403 - Permission denied

### ISSUE THREAD

**Issue by pagey101** [argoproj-labs/argocd-vault-plugin#488]
**Describe the bug**

Running the same version of argocd-vault-plugin on my Mac, vs on a Kubernetes pod, gives different results.

Vault audit log from Mac request (successful):

```
{
   "time":"2023-04-03T11:27:57.68799806Z",
   "type":"request",
   "auth":{
      "policy_results":{
         "allowed":true
      },
      "token_type":"default"
   },
   "request":{
      "id":"1b2bba8c-3bb5-6c43-526b-452acf736297",
      "operation":"update",
      "mount_type":"approle",
      "mount_accessor":"auth_approle_d85f4cf4",
      "namespace":{
         "id":"root"
      },
      "path":"auth/approle/login",
      "data":{
         "role_id":"hmac-sha256:fd5e07bc58f440085cf9ba1ebf661d3670d5810e17cb52a784eda70b37e4fb03",
         "secret_id":"hmac-sha256:8482ada25894603d67a254ff7e5dddffae604739040e4ef3a7589ccb8dddcca0"
      },
      "remote_address":"172.19.0.2",
      "remote_port":57468
   }
}
```

Vault audit log from Kubernetes pod request (permission denied):

```
{
   "time":"2023-04-03T11:28:36.367372898Z",
   "type":"request",
   "auth":{
      "token_type":"default"
   },
   "request":{
      "id":"8f149d4c-4bf0-7fc2-6e63-9fc898898de4",
      "operation":"update",
      "namespace":{
         "id":"root"
      },
      "path":"approle/login",
      "data":{
         "role_id":"hmac-sha256:fd5e07bc58f440085cf9ba1ebf661d3670d5810e17cb52a784eda70b37e4fb03",
         "secret_id":"hmac-sha256:8482ada25894603d67a254ff7e5dddffae604739040e4ef3a7589ccb8dddcca0"
      },
      "remote_address":"172.19.0.2",
      "remote_port":55692
   },
   "error":"permission denied"
}
```

The notable difference in the requests is the request `path`, although I have not specified a path explicitly on either request (see the vault configuration I have included below).

**To Reproduce**

The same config file (`vault_configuration.yml`) was used with the below contents for requests on a MacBook, and the ArgoCD repository server Kubernetes pod (redacted):

```
VAULT_ADDR: https://vault.example.com
AVP_TYPE: vault
AVP_AUTH_TYPE: approle
AVP_ROLE_ID: dsalkdjasdl-asda-sd-asd-sda
AVP_SECRET_ID: fewfef-fewfwef-wfvfvv-sd
```

With the following command:

```
argocd-vault-plugin -c vault_configuration.yml generate - < secret.yml
```

Where `secret.yml` has the following content:

```
apiVersion: v1
kind: Secret
metadata:  
  name: test-vault
type: Opaque
stringData:
  test: "<path:kv/data/path/to/something#secret>"
```

**Expected behavior**

I expect commands to result in the same response, be that successful render, or permission denied.

As it is, I get success on the Mac and 403 from the pod.

**Screenshots/Verbose output**

N/A

If you've tried running `argocd-vault-plugin generate` with `--verbose-sensitive-output` to help debug, please include that output here after redacting any secrets.

**Additional context**

N/A

**Comment by pagey101** [comment]
I should have noted that the argocd-vault-plugin version is `argocd-vault-plugin v1.14.0 (98e3987befca45c9c2bdc2e915c37de7e5688b37) BuildDate: 2023-03-21T13:34:29Z` on both Mac and pod.

**Comment by werne2j** [comment]
When you say running in mac vs K8s pod, is that in Argo CD? Or some other way?

if Argo CD, can you share the manifests for how you’re registering the plugin?

**Comment by pagey101** [comment]
I'm getting a shell onto the argocd repo server container where the plugin binary is to test vault connection.

I'm running argocd-vault-plugin from command line so argo is not actually involved at this moment, thus I don't believe sharing the manifests will helpful at this point.

**Comment by werne2j** [comment]
Are you getting any logs? Did you try running with `--verbose-sensitive-output ` yo help debug?

To me is pretty clear the mount point is not correct in your repo server pod causing the 403.

how are you putting the binary in the pod? That is helpful to share.

**Comment by pagey101** [comment]
I've found it, there were environment variables set on the argocd pod setting the mount path to `approle` rather than `auth/approle`. When I manually change the environment variable it works.

However setting the `AVP_MOUNT_PATH` to `auth/approle` doesn't seem to have an effect (I expect the configuration file to override the environment variables).

**Comment by werne2j** [comment]
The env vars overwrite the config/secret files. So you will have to remove the env var from the argocd pod, or overwrite with an Application level env var if you can't remove it from the argocd pod.

**Comment by pagey101** [comment]
Fair enough, thanks!
