### ISSUE TITLE
Manifest generation error 

### ISSUE THREAD

**Issue by ps-hpoznanski** [argoproj-labs/argocd-vault-plugin#494]
Good morning, I have a problem using your plugin. I am using "InitContainer and configuration via argocd-cm ConfigMap".  Argo version: v2.6.7+5bcd846

Piece of my Configmap for plugin-helm:

`apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  configManagementPlugins: |
    - name: argocd-vault-plugin-helm
      init:
        command: [sh, -c]
        args: ["helm dependency build"]
      generate:
        command: ["bash", "-c"]
        args: ['helm template "$ARGOCD_APP_NAME" -f <(echo "$ARGOCD_ENV_helm_values") . | argocd-vault-plugin generate -s argocd-vault-plugin-credential']`

Im using AVP_VERSION 1.14.0. Secrets are added. I have a error:

`rpc error: code = Unknown desc = Manifest generation error (cached): `bash -c helm template "$ARGOCD_APP_NAME" -f <(echo "$ARGOCD_ENV_helm_values") . | argocd-vault-plugin generate -s argocd-vault-plugin-credential` failed exit status 1: Error: release name "network_ingress-nginx-external": invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53 Error: <path> argument required to generate manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name> --verbose-sensitive-output enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr`

It looks like its trying to add to relase name prefix with namespace dont know.

My app definition:

`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-external
spec:
  destination:
    server: name_of_server
    namespace: network
  project: network
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.6.0
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_values
          value: |
            controller:
              replicaCount: 2
              ingressClassResource:
                name: nginx-external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true`

**Comment by werne2j** [comment]
First, It looks like your command is not correct. 

`helm template "$ARGOCD_APP_NAME" -f <(echo "$ARGOCD_ENV_helm_values") . | argocd-vault-plugin generate -s argocd-vault-plugin-credential ` 

should be 

`helm template "$ARGOCD_APP_NAME" -f <(echo "$ARGOCD_ENV_helm_values") . | argocd-vault-plugin generate -s argocd-vault-plugin-credential -`

But I am curious why you are using AVP for an external helm chart with no placeholders to be replaced? I would suggest just using the native Helm integration.

**Comment by hiteshbedre** [comment]
Even I see the error related to regex is also valid. Release name "network_ingress-nginx-external" fail to match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$". The correct regex pattern should be "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$".
I have tested it too. Here is the demo: https://regex101.com/r/B3Kr0u/1
