### ISSUE TITLE
argoCD vault plugin does not connect to TLS enable vault

### ISSUE THREAD

**Issue by anilpally** [argoproj-labs/argocd-vault-plugin#503]
**argoCD` vault plugin does not connect to TLS enable vault**
I am trying to connect to Enterprise version of Hashicorp vault using argocd vault plugin.

Here is my application.yaml looks like, as per the error message its clear that communication is broken due to  certificate signed by unknown authority 

Error:

Unable to create application: application spec for vault-test is invalid: InvalidSpecError: Unable to generate manifests in vault-test: rpc error: code = Unknown desc = `argocd-vault-plugin generate ./` failed exit status 1: Error: Put https://iacvault-temp.iachelloworld.dev.abc.com:8200/v1/auth/kubernetes/login: x509: certificate signed by unknown authority Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name> --verbose-sensitive-output enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr

`apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:

  name: 'vault-test'

spec:
  destination:
    server:  'https://kubernetes.default.svc/'
  source:
    repoURL: 'https://bitbucket.abc.com/scm/~ping/cicd.git'
    path: vault-test
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
      env:
      - name: AVP_K8S_ROLE
        value: vplugin
      - name: AVP_TYPE
        value: vault
      - name: VAULT_ADDR
        value: 'https://iacvault-temp.iachelloworld.dev.abc.com:8200/'
      - name: AVP_AUTH_TYPE 
         value: k8s
project: 'default'
`

**Comment by werne2j** [comment]
Related issues:
https://github.com/argoproj-labs/argocd-vault-plugin/issues/456
https://github.com/argoproj-labs/argocd-vault-plugin/issues/52

You can use any Vault environment variables such as:
VAULT_CACERT
VAULT_CAPATH
VAULT_CLIENT_CERT
VAULT_CLIENT_KEY

**Comment by anilpally** [comment]
can be closed
