### ISSUE TITLE
Add kubernetes secrets backend

### ISSUE THREAD

**Issue by acelinkio** [argoproj-labs/argocd-vault-plugin#516]
**Is your feature request related to a problem? Please describe.**
ArgoVaultPlugin provides a simple method for performing string replacements on any object deployed by ArgoCD.  I regularly work with ephemeral Kubernetes clusters for development and would like to avoid making a large number of requests to real backends.  

**Describe the solution you'd like**
Add support for using local Kubernetes secrets as a backend.  

**Describe alternatives you've considered**
SOPS backend.  Requires that a file is checked into a repository which is not ideal for ephemeral development resources.

**Additional context**
This may seem redundant, however many objects do not support the native use of secrets.  Leveraging ArgoVaultPlugin for basic manipulation enables local development to reuse the same structures expected in production.

**Comment by dennislapchenko** [comment]
We have decided to go this way as well. Planning to finish a solution in the next week or so. Hopefully as an addition to this plugin, else - as a separate plugin.

**Comment by acelinkio** [comment]
Closed with 1.16 release
