### ISSUE TITLE
IBM Secrets Manager V2 API update

### ISSUE THREAD

**Issue by quixote65** [argoproj-labs/argocd-vault-plugin#517]
**Is your feature request related to a problem? Please describe.**
The current IBM Cloud Secrets Manager support is based on the Version 1 API. 
This API version will cease to work October 31, 2023.

**Describe the solution you'd like**
The current solution will need to be upgraded to the IBM Cloud Secrets Manager Version2 API. This will require migrating to the [v2 GO sdk](https://github.com/IBM/secrets-manager-go-sdk)

**Comment by werne2j** [comment]
PR already in the works https://github.com/argoproj-labs/argocd-vault-plugin/pull/513

**Comment by werne2j** [comment]
Update to v2 released with https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.15.0
