### ISSUE TITLE
delineasecretserver is not supported

### ISSUE THREAD

**Issue by HSoulat** [argoproj-labs/argocd-vault-plugin#570]
**Describe the bug**
delineasecretserver do not seems supported by v1.15.0 & v1.16.1 plugin.

**To Reproduce**
Configure plugin to use Delinea Sercret Server 

```
generate:
        command:
          - argocd-vault-plugin
          - generate
          - "-s"
          - "vault-configuration"
          - "."
```

```
apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
data:
  AVP_TYPE: ZGVsaW5lYXNlY3JldHNlcnZlcgo=
  AVP_DELINEA_URL: ...
  AVP_DELINEA_USER: ...
  AVP_DELINEA_PASSWORD: ...
type: Opaque
```

If we try to execute the generate from avp container : `argocd-vault-plugin generate -s vault-configuration .`
`Error: Must provide a supported Vault Type, received delineasecretserver`

**Expected behavior**
Since version v1.15.0 this backend is marked as supported.

**Screenshots/Verbose output**

```
2023/10/26 09:45:53 reading configuration from secret vault-configuration
2023/10/26 09:45:53 reading configuration from environment, overriding any previous settings
2023/10/26 09:45:53 AVP configured with the following settings:

2023/10/26 09:45:53 avp_delinea_password: ...


2023/10/26 09:45:53 avp_delinea_url: ...


2023/10/26 09:45:53 avp_kv_version: 2

2023/10/26 09:45:53 avp_delinea_user: ...


2023/10/26 09:45:53 avp_type: delineasecretserver


Error: Must provide a supported Vault Type, received delineasecretserver
```

**Comment by HSoulat** [comment]
I may be wrong but it seems that import in pkg/config/config.go point to an incorrect url. 
`delineasecretserver "github.com/DelineaXPM/tss-sdk-go/v2/server"` should be `delineasecretserver "github.com/DelineaXPM/tss-sdk-go/server"`

**Comment by werne2j** [comment]
Check the value of the type to make sure there isn’t a newline at the end. https://github.com/argoproj-labs/argocd-vault-plugin/issues/301#issuecomment-1045174207

**Comment by HSoulat** [comment]
@werne2j thanks, that was a newline at the end of base64 value.
