### ISSUE TITLE
Access to vault with custom certificate

### ISSUE THREAD

**Issue by HSoulat** [argoproj-labs/argocd-vault-plugin#572]
I have configured  the plugin to connect to a remote delinea server. Unfortunaltely I got an x509: certificate signed by unknown authority error. 

I've tried to : 
- add the CA chain in sidecar container image trust store 
- add the CA chain in argocd `/app/config/tls.
- use VAULT_SKIP_VERIFY option

As the solutions doesn't work. Is there a documentation who list where the plugin is retreiving the trusted CA ?

**Comment by werne2j** [comment]
https://github.com/argoproj-labs/argocd-vault-plugin/issues/503

**Comment by HSoulat** [comment]
thanks !
