### ISSUE TITLE
Large number of vulnerabilities in argocd-vault-plugin 1.16.1

### ISSUE THREAD

**Issue by dvasilen** [argoproj-labs/argocd-vault-plugin#574]
The latest released version of the plugin `1.16.1` has been compiled against golang `1.17.8`. There are a large number of vulnerabilities reported. Could you please provide an ETA for the next release of the plugin compiled against golang `1.21.x`?

**Comment by werne2j** [comment]
https://github.com/argoproj-labs/argocd-vault-plugin/pull/565 Hope to create a new release soon

**Comment by werne2j** [comment]
New release https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.17.0
