### ISSUE TITLE
Does this plugin work with argo v2.8 ? 

### ISSUE THREAD

**Issue by SnoozeFreddo** [argoproj-labs/argocd-vault-plugin#585]
Hi there,

https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.7-2.8/

says that Config Management Plugins installed via the argocd-cm ConfigMap will not work starting with v2.8..

There are two [installation](https://argocd-vault-plugin.readthedocs.io/en/stable/installation/) methods in the argocd-vault-plugin docs. One is via sidecar and the second via Configmap.  There are pre-build kustomize apps, but both have ConfigManagementPlugin defined in them.

Does that mean that this plugin doesn't work yet with argo version 2.8+ ?

**Comment by werne2j** [comment]
Yes, it works with the side car method. Example manifests https://github.com/argoproj-labs/argocd-vault-plugin/tree/main/manifests/cmp-sidecar
